export const RIVALRY_STORY_TEMPLATES = [
  {
    key: 'receipts-due',
    relationshipTypes: ['Rival'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Receipts Due`,
    hook: ({ first, second }) => `${first.name} and ${second.name} refuse to let the last exchange define who owns the ring.`,
    openingSegment: ({ first, second }) => `${first.name} calls out ${second.name} and demands the score be settled face-to-face.`,
    openingMatch: ({ first, second }) => `${first.name} and ${second.name} meet in a tense singles match that breaks down after tempers spill over.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} settle it in a decisive rematch where one wrestler finally earns the last word.`,
  },
  {
    key: 'line-in-the-mat',
    relationshipTypes: ['Rival'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Line in the Mat`,
    hook: ({ first, second }) => `${first.name} and ${second.name} both believe the other is standing in the way of their next step.`,
    openingSegment: ({ first, second }) => `${second.name} interrupts ${first.name} and makes it clear there is only room for one of them to rise.`,
    openingMatch: ({ first, second }) => `${first.name} faces a hand-picked opponent while ${second.name} watches closely from ringside.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} meet with no excuses left, proving who truly belongs ahead of the other.`,
  },
  {
    key: 'bad-blood-burns',
    relationshipTypes: ['Rival', 'Betrayed'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Bad Blood Burns`,
    hook: ({ first, second, relationship }) => (
      relationship.type === 'Betrayed'
        ? `${first.name} cannot move past what ${second.name} did.`
        : `${first.name} and ${second.name} have turned competition into something personal.`
    ),
    openingSegment: ({ first, second }) => `${first.name} confronts ${second.name} in the ring and forces the tension into the open.`,
    openingMatch: ({ first, second }) => `${first.name} and ${second.name} are kept apart at first, but every match around them turns into a message.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} finally collide in a match where the anger has nowhere left to hide.`,
  },
  {
    key: 'partners-no-more',
    relationshipTypes: ['Former Partner'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Partners No More`,
    hook: ({ first, second }) => `${first.name} and ${second.name} know each other too well, and that makes every move personal.`,
    openingSegment: ({ first, second }) => `${first.name} reminds ${second.name} that shared history does not erase unfinished resentment.`,
    openingMatch: ({ first, second }) => `${first.name} and ${second.name} face separate opponents while countering each other's familiar habits from afar.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} settle the split by proving who grew stronger after the partnership ended.`,
  },
  {
    key: 'old-playbook-new-grudge',
    relationshipTypes: ['Former Partner'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Old Playbook, New Grudge`,
    hook: ({ first, second }) => `${first.name} and ${second.name} keep using their shared past as a weapon against each other.`,
    openingSegment: ({ first, second }) => `${second.name} breaks down ${first.name}'s weaknesses in a pointed promo built on familiarity.`,
    openingMatch: ({ first, second }) => `${first.name} wrestles while ${second.name} gives commentary on every mistake and opening.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} fight through every old counter until one finally rewrites the ending.`,
  },
  {
    key: 'trust-was-the-setup',
    relationshipTypes: ['Betrayed'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Trust Was the Setup`,
    hook: ({ first, second }) => `${first.name} wants answers, but ${second.name} treats the betrayal like a smart career move.`,
    openingSegment: ({ first, second }) => `${first.name} demands an explanation while ${second.name} refuses to show regret.`,
    openingMatch: ({ first, second }) => `${first.name} takes a match while ${second.name} tries to distract them from the floor.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} meet in a grudge match where payback and justification collide.`,
  },
  {
    key: 'knife-in-the-spotlight',
    relationshipTypes: ['Betrayed'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Knife in the Spotlight`,
    hook: ({ first, second }) => `${second.name} stepped over ${first.name}, and now ${first.name} wants the spotlight turned into evidence.`,
    openingSegment: ({ first, second }) => `${first.name} replays the betrayal in words and dares ${second.name} to defend it live.`,
    openingMatch: ({ first, second }) => `${second.name} competes first, with ${first.name} watching for any sign of weakness.`,
    payoff: ({ first, second }) => `${first.name} forces ${second.name} into a final reckoning where the betrayal must either pay off or backfire.`,
  },
  {
    key: 'last-page-unwritten',
    relationshipTypes: ['Unfinished Business'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Last Page Unwritten`,
    hook: ({ first, second }) => `${first.name} and ${second.name} have a chapter that never got a clean ending.`,
    openingSegment: ({ first, second }) => `${first.name} says the issue with ${second.name} has been delayed long enough.`,
    openingMatch: ({ first, second }) => `${first.name} and ${second.name} are placed on opposite sides of a tense preview match.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} finish what was left hanging with a clear winner and no asterisk.`,
  },
  {
    key: 'no-more-what-ifs',
    relationshipTypes: ['Unfinished Business', 'Rival'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: No More What-Ifs`,
    hook: ({ first, second }) => `${first.name} and ${second.name} are tired of hearing excuses attached to their names.`,
    openingSegment: ({ first, second }) => `${second.name} claims ${first.name} has been hiding behind doubt, timing, and circumstance.`,
    openingMatch: ({ first, second }) => `${first.name} and ${second.name} each compete under pressure to prove they are ready now.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} answer every what-if in one final match.`,
  },
  {
    key: 'earned-not-given',
    relationshipTypes: ['Respect'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Earned, Not Given`,
    hook: ({ first, second }) => `${first.name} and ${second.name} respect each other, but respect alone does not decide who is better.`,
    openingSegment: ({ first, second }) => `${first.name} offers respect to ${second.name}, then asks for the chance to test it in the ring.`,
    openingMatch: ({ first, second }) => `${first.name} and ${second.name} compete in a clean match that grows sharper with every exchange.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} close the rivalry with a match built on skill, pride, and a final handshake.`,
  },
  {
    key: 'honor-has-teeth',
    relationshipTypes: ['Respect'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Honor Has Teeth`,
    hook: ({ first, second }) => `${first.name} and ${second.name} keep it respectful, but neither is willing to wrestle softly.`,
    openingSegment: ({ first, second }) => `${second.name} praises ${first.name} before warning that admiration will not stop the fight.`,
    openingMatch: ({ first, second }) => `${first.name} faces ${second.name} in a hard-hitting opener where restraint starts to crack.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} prove respect can survive a war when the better wrestler stands tall.`,
  },
  {
    key: 'lesson-turns-live',
    relationshipTypes: ['Mentor', 'Student'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Lesson Turns Live`,
    hook: ({ first, second }) => `${first.name} and ${second.name} turn guidance into conflict when pride enters the ring.`,
    openingSegment: ({ first, second }) => `${first.name} questions whether ${second.name} is ready to learn the hard way.`,
    openingMatch: ({ first, second }) => `${second.name} is tested in a match while ${first.name} studies every decision from ringside.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} meet in a match where the lesson becomes the fight itself.`,
  },
  {
    key: 'surpass-the-standard',
    relationshipTypes: ['Student', 'Mentor'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Surpass the Standard`,
    hook: ({ first, second }) => `${first.name} wants proof that ${second.name} can no longer define their ceiling.`,
    openingSegment: ({ first, second }) => `${first.name} tells ${second.name} that respect has become a cage, not a compass.`,
    openingMatch: ({ first }) => `${first.name} takes a demanding match meant to show they no longer need approval.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} settle whether the student has truly passed the standard.`,
  },
  {
    key: 'ally-under-pressure',
    relationshipTypes: ['Ally'],
    name: ({ first, second }) => `${first.name} and ${second.name}: Ally Under Pressure`,
    hook: ({ first, second }) => `${first.name} and ${second.name} are allies, but tension rises when trust starts feeling like a test.`,
    openingSegment: ({ first, second }) => `${first.name} asks ${second.name} for clarity after a moment of hesitation creates doubt.`,
    openingMatch: ({ first, second }) => `${first.name} and ${second.name} must cooperate in a difficult match while frustration builds.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} either restore trust or admit the alliance cannot survive the pressure.`,
  },
  {
    key: 'favor-comes-due',
    relationshipTypes: ['Owes Favor'],
    name: ({ first, second }) => `${first.name} and ${second.name}: Favor Comes Due`,
    hook: ({ first, second, relationship }) => relationship.note || `${second.name} believes ${first.name} owes them, and the debt is becoming impossible to ignore.`,
    openingSegment: ({ first, second }) => `${second.name} reminds ${first.name} that favors have weight in this business.`,
    openingMatch: ({ first, second }) => `${first.name} is pressured into a match shaped by ${second.name}'s expectations.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} resolve the debt, either through repayment or a fight over its cost.`,
  },
  {
    key: 'pressure-makes-enemies',
    relationshipTypes: ['Rival', 'Ally', 'Respect', 'Unfinished Business'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Pressure Makes Enemies`,
    hook: ({ first, second }) => `${first.name} and ${second.name} are pushed into conflict when pride becomes louder than patience.`,
    openingSegment: ({ first, second }) => `${first.name} and ${second.name} trade sharp words after a tense moment refuses to fade.`,
    openingMatch: ({ first, second }) => `${first.name} and ${second.name} are booked in separate tests with each watching the other's result.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} settle the pressure in a match that reveals what the relationship can survive.`,
  },
  {
    key: 'nothing-left-to-say',
    relationshipTypes: ['Rival', 'Betrayed', 'Unfinished Business', 'Former Partner'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Nothing Left to Say`,
    hook: ({ first, second }) => `${first.name} and ${second.name} have talked themselves into a fight that words can no longer control.`,
    openingSegment: ({ first, second }) => `${first.name} cuts off ${second.name}'s explanation and demands action instead of another excuse.`,
    openingMatch: ({ first, second }) => `${first.name} and ${second.name} are kept from a clean finish, making the issue even harder to contain.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} end the rivalry in a straight fight where the result says everything.`,
  },
  {
    key: 'eye-contact-heat',
    relationshipTypes: ['Rival', 'Betrayed', 'Unfinished Business', 'Former Partner'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Eye Contact Heat`,
    hook: ({ first, second }) => `${first.name} and ${second.name} do not need long speeches because one look says enough.`,
    openingSegment: ({ first, second }) => `${first.name} and ${second.name} share a staredown that turns the room against silence.`,
    openingMatch: ({ first, second }) => `${first.name} wrestles while ${second.name} watches closely enough to become the story.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} finally turn the staredown into a fight with no room left for restraint.`,
  },
  {
    key: 'professional-until-bell',
    relationshipTypes: ['Rival', 'Respect', 'Mentor', 'Student'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Professional Until Bell`,
    hook: ({ first, second }) => `${first.name} and ${second.name} try to keep the conflict controlled until competition makes it personal.`,
    openingSegment: ({ first, second }) => `${second.name} keeps the words measured, but ${first.name} hears the challenge underneath.`,
    openingMatch: ({ first, second }) => `${first.name} and ${second.name} start with a clean match that grows less polite with every exchange.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} decide the issue when professionalism finally gives way to pride.`,
  },
  {
    key: 'heat-check',
    relationshipTypes: ['Rival', 'Ally', 'Respect', 'Unfinished Business', 'Former Partner', 'Betrayed', 'Owes Favor'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Heat Check`,
    hook: ({ first, second }) => `${first.name} and ${second.name} test whether the tension between them is temporary or ready to explode.`,
    openingSegment: ({ first, second }) => `${first.name} presses ${second.name} with one question: is this a problem or a fight?`,
    openingMatch: ({ first, second }) => `${second.name} answers through action, forcing ${first.name} to respond before the night is over.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} reach the payoff when the tension finally becomes a clear result.`,
  },
  {
    key: 'cold-open-callout',
    relationshipTypes: ['Rival'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Cold Open Callout`,
    hook: ({ first, second }) => `${first.name} wants a fight, and ${second.name} refuses to back down from the challenge.`,
    openingSegment: ({ first, second }) => `${first.name} opens the show by calling ${second.name} out before the night can even settle.`,
    openingMatch: ({ first, second }) => `${second.name} answers with action, forcing ${first.name} into a match that tests their focus.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} close the issue in a heated match built on pride and pressure.`,
  },
  {
    key: 'friendly-fire-warning',
    relationshipTypes: ['Ally', 'Respect'],
    name: ({ first, second }) => `${first.name} and ${second.name}: Friendly Fire Warning`,
    hook: ({ first, second }) => `${first.name} and ${second.name} remain connected, but competitive pride keeps putting them at odds.`,
    openingSegment: ({ first, second }) => `${second.name} tells ${first.name} that loyalty does not mean stepping aside.`,
    openingMatch: ({ first, second }) => `${first.name} and ${second.name} are paired together and nearly lose focus when pride takes over.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} face each other to clear the air before the bond breaks completely.`,
  },
  {
    key: 'debt-with-interest',
    relationshipTypes: ['Owes Favor'],
    name: ({ first, second }) => `${first.name} and ${second.name}: Debt with Interest`,
    hook: ({ first, second }) => `${second.name} wants more than gratitude from ${first.name}; they want leverage.`,
    openingSegment: ({ first, second }) => `${second.name} publicly calls in the favor and puts ${first.name} on the spot.`,
    openingMatch: ({ first, second }) => `${first.name} tries to handle business while ${second.name} keeps raising the emotional price.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} decide whether the favor ends in loyalty, resentment, or a clean break.`,
  },
  {
    key: 'prove-it-again',
    relationshipTypes: ['Rival', 'Respect', 'Unfinished Business', 'Former Partner'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Prove It Again`,
    hook: ({ first, second }) => `${first.name} and ${second.name} both believe one more match will expose the truth.`,
    openingSegment: ({ first, second }) => `${second.name} challenges ${first.name} to stop talking about proof and start providing it.`,
    openingMatch: ({ first, second }) => `${first.name} earns momentum in a match while ${second.name} refuses to be impressed.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} meet again with pride, momentum, and bragging rights on the line.`,
  },
  {
    key: 'prove-the-point',
    relationshipTypes: ['Rival'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Prove the Point`,
    hook: ({ first, second }) => `${first.name} and ${second.name} are locked in a fight over whose confidence is earned and whose is empty noise.`,
    openingSegment: ({ first, second }) => `${first.name} challenges ${second.name} to back up every word in front of the crowd.`,
    openingMatch: ({ first, second }) => `${second.name} takes a match designed to send ${first.name} a message without direct contact.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} settle the argument in a match where the result becomes the only point that matters.`,
  },
  {
    key: 'ring-space-dispute',
    relationshipTypes: ['Rival'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Ring Space Dispute`,
    hook: ({ first, second }) => `${first.name} and ${second.name} both act like the ring belongs to them, and neither is willing to move aside.`,
    openingSegment: ({ first, second }) => `${second.name} interrupts ${first.name} and refuses to leave until respect is forced out of them.`,
    openingMatch: ({ first, second }) => `${first.name} wrestles under pressure while ${second.name} makes their presence impossible to ignore.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} fight until one wrestler controls the ring and the other has to accept it.`,
  },
  {
    key: 'one-step-ahead',
    relationshipTypes: ['Rival', 'Unfinished Business'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: One Step Ahead`,
    hook: ({ first, second }) => `${first.name} and ${second.name} keep trying to outthink each other before they ever lock up.`,
    openingSegment: ({ first, second }) => `${first.name} lays out exactly how ${second.name} can be beaten, daring them to prove otherwise.`,
    openingMatch: ({ first, second }) => `${second.name} competes with ${first.name} scouting from close range and looking for patterns.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} reach the payoff when instinct finally beats planning or planning finally wins out.`,
  },
  {
    key: 'grudge-in-motion',
    relationshipTypes: ['Rival', 'Betrayed'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Grudge in Motion`,
    hook: ({ first, second }) => `${first.name} and ${second.name} cannot share a show without the issue pulling everything toward them.`,
    openingSegment: ({ first, second }) => `${first.name} confronts ${second.name} before officials can keep the situation controlled.`,
    openingMatch: ({ first, second }) => `${first.name} is booked in a match that becomes chaotic once ${second.name} gets involved verbally.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} finally get a sanctioned fight where the grudge can burn itself out.`,
  },
  {
    key: 'split-decision',
    relationshipTypes: ['Former Partner'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Split Decision`,
    hook: ({ first, second }) => `${first.name} and ${second.name} disagree on what their past meant and what their future should prove.`,
    openingSegment: ({ first, second }) => `${second.name} says ${first.name} was never the reason the partnership worked.`,
    openingMatch: ({ first, second }) => `${first.name} wrestles someone with ${second.name} studying the habits they used to know best.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} settle who carried the past and who is stronger without it.`,
  },
  {
    key: 'familiar-counters',
    relationshipTypes: ['Former Partner', 'Respect'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Familiar Counters`,
    hook: ({ first, second }) => `${first.name} and ${second.name} know every rhythm, every escape, and every mistake the other can make.`,
    openingSegment: ({ first, second }) => `${first.name} warns ${second.name} that familiarity cuts both ways.`,
    openingMatch: ({ first, second }) => `${first.name} and ${second.name} test each other in a match that turns into a chess match of reversals.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} end it when one finally finds something the other has never seen before.`,
  },
  {
    key: 'the-break-wasnt-clean',
    relationshipTypes: ['Former Partner', 'Unfinished Business'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: The Break Wasn't Clean`,
    hook: ({ first, second }) => `${first.name} and ${second.name} moved on in public, but the tension never really left.`,
    openingSegment: ({ first, second }) => `${second.name} accuses ${first.name} of pretending the past ended neatly.`,
    openingMatch: ({ first, second }) => `${first.name} and ${second.name} are forced into the same orbit and struggle to keep old issues buried.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} finish the breakup with a match that finally makes the separation real.`,
  },
  {
    key: 'betrayal-in-plain-sight',
    relationshipTypes: ['Betrayed'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Betrayal in Plain Sight`,
    hook: ({ first, second }) => `${first.name} believes everyone saw the betrayal except ${second.name}, who still tries to justify it.`,
    openingSegment: ({ first, second }) => `${first.name} calls ${second.name} to the ring and demands they say the truth out loud.`,
    openingMatch: ({ first, second }) => `${second.name} competes while ${first.name} watches, waiting for the same selfish pattern to show again.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} collide when the betrayal becomes impossible to spin or deny.`,
  },
  {
    key: 'payback-position',
    relationshipTypes: ['Betrayed', 'Rival'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Payback Position`,
    hook: ({ first, second }) => `${first.name} wants justice, while ${second.name} insists payback is just another word for weakness.`,
    openingSegment: ({ first, second }) => `${second.name} taunts ${first.name} for still being stuck on what happened.`,
    openingMatch: ({ first }) => `${first.name} takes a physical test meant to prove emotion will not ruin their focus.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} settle whether revenge can be controlled once the bell rings.`,
  },
  {
    key: 'unfinished-sentence',
    relationshipTypes: ['Unfinished Business'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Unfinished Sentence`,
    hook: ({ first, second }) => `${first.name} and ${second.name} have never been able to finish the statement they started in the ring.`,
    openingSegment: ({ first, second }) => `${first.name} says every conversation about ${second.name} still ends with a question mark.`,
    openingMatch: ({ first, second }) => `${second.name} competes while ${first.name} makes it clear the issue is being reopened.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} finally complete the sentence with a clean result.`,
  },
  {
    key: 'the-match-that-wouldnt-end',
    relationshipTypes: ['Unfinished Business', 'Rival'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: The Match That Wouldn't End`,
    hook: ({ first, second }) => `${first.name} and ${second.name} keep circling back to one fight that never felt fully settled.`,
    openingSegment: ({ first, second }) => `${second.name} says ${first.name} has been living off an unresolved moment for too long.`,
    openingMatch: ({ first, second }) => `${first.name} and ${second.name} are placed near each other without getting the match they want yet.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} get the match that should have ended everything the first time.`,
  },
  {
    key: 'mutual-measure',
    relationshipTypes: ['Respect'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Mutual Measure`,
    hook: ({ first, second }) => `${first.name} and ${second.name} respect each other because both know the other is a real measuring stick.`,
    openingSegment: ({ first, second }) => `${first.name} invites ${second.name} to prove respect through competition instead of compliments.`,
    openingMatch: ({ first, second }) => `${first.name} and ${second.name} start clean, but the match grows more urgent with every near fall.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} finish with one winner and both reputations strengthened.`,
  },
  {
    key: 'respect-at-full-speed',
    relationshipTypes: ['Respect'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Respect at Full Speed`,
    hook: ({ first, second }) => `${first.name} and ${second.name} admire each other enough to hold nothing back.`,
    openingSegment: ({ first, second }) => `${second.name} tells ${first.name} that respect means giving them the hardest fight possible.`,
    openingMatch: ({ first, second }) => `${first.name} and ${second.name} test the pace early in a match built on clean escalation.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} reach a final match where respect is proven by survival, not words.`,
  },
  {
    key: 'hard-lesson',
    relationshipTypes: ['Mentor', 'Student'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Hard Lesson`,
    hook: ({ first, second }) => `${first.name} and ${second.name} turn a lesson into a conflict when patience gives way to pride.`,
    openingSegment: ({ first, second }) => `${first.name} says ${second.name} is mistaking advice for disrespect.`,
    openingMatch: ({ first, second }) => `${second.name} enters a match under scrutiny while ${first.name} watches for growth or failure.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} settle the lesson in the ring, where the result teaches both of them something.`,
  },
  {
    key: 'outgrow-the-shadow',
    relationshipTypes: ['Student', 'Mentor'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Outgrow the Shadow`,
    hook: ({ first, second }) => `${first.name} wants to stop being compared to ${second.name} and start being judged alone.`,
    openingSegment: ({ first, second }) => `${first.name} tells ${second.name} that guidance has become a shadow they need to escape.`,
    openingMatch: ({ first, second }) => `${first.name} is tested in a match where every success is still framed around ${second.name}.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} meet so ${first.name} can prove whether the shadow is finally gone.`,
  },
  {
    key: 'teacher-tested',
    relationshipTypes: ['Mentor', 'Student', 'Respect'],
    name: ({ first, second }) => `${first.name} vs ${second.name}: Teacher Tested`,
    hook: ({ first, second }) => `${first.name} and ${second.name} both believe the best lesson now requires direct contact.`,
    openingSegment: ({ first, second }) => `${second.name} challenges ${first.name} to stop evaluating from a distance.`,
    openingMatch: ({ first, second }) => `${first.name} and ${second.name} begin with a controlled match that becomes more intense than expected.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} end the test with one proving readiness and the other forced to acknowledge it.`,
  },
  {
    key: 'alliance-cracks',
    relationshipTypes: ['Ally'],
    name: ({ first, second }) => `${first.name} and ${second.name}: Alliance Cracks`,
    hook: ({ first, second }) => `${first.name} and ${second.name} are still allies, but every choice starts to feel like a side is being chosen.`,
    openingSegment: ({ first, second }) => `${first.name} asks ${second.name} whether loyalty still means the same thing to both of them.`,
    openingMatch: ({ first, second }) => `${first.name} and ${second.name} share a match where one mistake nearly costs them everything.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} either repair the alliance or let the cracks become the story.`,
  },
  {
    key: 'same-side-different-goals',
    relationshipTypes: ['Ally'],
    name: ({ first, second }) => `${first.name} and ${second.name}: Same Side, Different Goals`,
    hook: ({ first, second }) => `${first.name} and ${second.name} want success, but not at the same pace or the same cost.`,
    openingSegment: ({ first, second }) => `${second.name} tells ${first.name} that being allies does not mean wanting the same thing.`,
    openingMatch: ({ first, second }) => `${first.name} and ${second.name} work together, but their priorities clash under pressure.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} decide whether the alliance can survive ambition pulling them apart.`,
  },
  {
    key: 'favor-as-leverage',
    relationshipTypes: ['Owes Favor'],
    name: ({ first, second }) => `${first.name} and ${second.name}: Favor as Leverage`,
    hook: ({ first, second, relationship }) => relationship.note || `${second.name} treats the favor ${first.name} owes as power, not history.`,
    openingSegment: ({ first, second }) => `${second.name} reminds ${first.name} that a debt ignored becomes a problem.`,
    openingMatch: ({ first, second }) => `${first.name} is pulled into a difficult match because ${second.name} insists the favor matters now.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} settle whether the favor was loyalty, leverage, or a mistake.`,
  },
  {
    key: 'called-in-public',
    relationshipTypes: ['Owes Favor'],
    name: ({ first, second }) => `${first.name} and ${second.name}: Called in Public`,
    hook: ({ first, second }) => `${second.name} chooses the worst possible moment to remind ${first.name} that a favor is still owed.`,
    openingSegment: ({ first, second }) => `${second.name} calls in the favor in front of everyone and leaves ${first.name} no easy answer.`,
    openingMatch: ({ first, second }) => `${first.name} competes while the pressure of ${second.name}'s demand hangs over the match.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} resolve the debt once public pressure turns into direct conflict.`,
  },
  {
    key: 'bad-timing',
    relationshipTypes: ['Rival', 'Ally', 'Respect', 'Unfinished Business', 'Owes Favor'],
    name: ({ first, second }) => `${first.name} and ${second.name}: Bad Timing`,
    hook: ({ first, second }) => `${first.name} and ${second.name} might have handled things differently if the pressure had not arrived all at once.`,
    openingSegment: ({ first, second }) => `${first.name} tries to address ${second.name}, but the moment turns sharper than intended.`,
    openingMatch: ({ first, second }) => `${second.name} enters a match with ${first.name}'s presence changing the emotional temperature.`,
    payoff: ({ first, second }) => `${first.name} and ${second.name} settle whether the conflict was bad timing or something deeper.`,
  },
]
