export const HEATSPARK_WHEEL_ENTRIES = [
  { id: 'medical-suspension', title: 'Medical Suspension', description: 'A random superstar is ruled out for two weeks and cannot compete, but may still appear in segments.', category: 'Pressure' },
  { id: 'brand-transfer', title: 'Transfer Request', description: 'A random superstar demands a move to the other brand. Start the negotiation and decide the price.', category: 'Brands' },
  { id: 'iron-man', title: 'Iron Man Rivalry', description: 'A rivalry must end in a 30-minute Iron Man Match at the next major event.', category: 'Rivalry' },
  { id: 'brand-invasion', title: 'Brand Invasion', description: 'One brand may steal a superstar from the other brand and deal with the fallout.', category: 'Brands' },
  { id: 'underdog-midcard', title: 'Underdog Push', description: 'A low-ranked or underused superstar gets a midcard title match at the next PPV.', category: 'Push' },
  { id: 'faction-chaos', title: 'Faction Chaos', description: 'Create a new faction of 3 to 5 randomly selected superstars.', category: 'Faction' },
  { id: 'identity-theft', title: 'Identity Theft', description: 'A random superstar copies another wrestler’s complete character until the original defeats them at a PPV.', category: 'Character' },
  { id: 'heel-turn', title: 'Heel Turn', description: 'A random fan favorite turns villain and immediately needs a new direction.', category: 'Character' },
  { id: 'betrayal', title: 'Sudden Betrayal', description: 'A random tag team breaks up immediately. The former partners become a new rivalry.', category: 'Rivalry' },
  { id: 'new-champion', title: 'We Need Gold', description: 'Introduce a new secondary championship to the universe.', category: 'Championship' },
  { id: 'faction-war', title: 'Faction War', description: 'Two factions feud until the next PPV, ending in a Survivor Series-style elimination match.', category: 'Faction' },
  { id: 'rookie-main-event', title: 'Rookie Spotlight', description: 'Only low-ranked or underused wrestlers may compete in this week’s main event.', category: 'Push' },
  { id: 'wild-card', title: 'Wild Card Rule', description: 'For the next four weeks, each show may use three wrestlers from the opposite brand.', category: 'Brands' },
  { id: 'mascot-duty', title: 'Mascot Duty', description: 'A serious main-event wrestler receives a ridiculous character and must team with a low-card wrestler for four weeks.', category: 'Character' },
  { id: 'giant-killer', title: 'Giant Killer', description: 'A low-ranked superstar must defeat a main-eventer within three matches or be released.', category: 'Pressure' },
  { id: 'evil-twin', title: 'Evil Twin Debut', description: 'Remix a random fan favorite into a darker alter ego with a new name and presentation.', category: 'Character' },
  { id: 'open-challenge-chaos', title: 'Open Challenge Chaos', description: 'A random champion defends every week until the next PPV, ending in a gauntlet if they remain champion.', category: 'Championship' },
  { id: 'manager-favorite', title: 'GM’s Favorite', description: 'A random superstar receives two title opportunities during the next month.', category: 'Authority' },
  { id: 'steel-cage-week', title: 'Steel Cage Week', description: 'Every active rivalry match booked this week must happen inside a Steel Cage.', category: 'Stipulation' },
  { id: 'budget-cut', title: 'Salary Cap Cut', description: 'Release the three highest-rated non-champions from a selected brand.', category: 'Pressure' },
  { id: 'nxt-invasion', title: 'Developmental Invasion', description: 'Five developmental wrestlers invade the main show as a faction and demand contracts.', category: 'Brands' },
  { id: 'legend-returns', title: 'Legend Returns', description: 'Bring in a legend for a one-month run. The deal becomes permanent if they win a championship.', category: 'Special' },
  { id: 'random-draft', title: 'Random Draft', description: 'Each brand trades three randomly selected superstars.', category: 'Brands' },
  { id: 'ladder-title', title: 'Ladder Title Match', description: 'The next championship match must be contested under Ladder Match rules.', category: 'Stipulation' },
  { id: 'manager-arrives', title: 'Manager Appears', description: 'Assign a manager to a random superstar, who immediately targets the secondary champion.', category: 'Authority' },
  { id: 'dominant-streak', title: 'Dominant Streak', description: 'A random superstar must win five consecutive matches. Success earns a title shot; failure means release.', category: 'Pressure' },
  { id: 'champion-vs-world', title: 'Champion Against the World', description: 'Your world champion defends against a 30-person Royal Rumble-style field at the next PPV.', category: 'Championship' },
  { id: 'triple-threat-addition', title: 'Triple Threat Chaos', description: 'Add a random superstar to a championship match at the next PPV.', category: 'Championship' },
  { id: 'last-chance', title: 'Last Chance Match', description: 'A random superstar must win their next match or be released.', category: 'Pressure' },
  { id: 'apocalypse-ppv', title: 'Apocalypse PPV', description: 'The next PPV may contain only matches with special stipulations. No standard match is allowed.', category: 'Stipulation' },
  { id: 'faction-collapse', title: 'Faction Collapse', description: 'A random faction breaks apart immediately, sending all members into separate rivalries.', category: 'Faction' },
  { id: 'champion-injury', title: 'Champion Injury', description: 'A random champion is out for three months and must vacate the title.', category: 'Championship' },
  { id: 'character-swap', title: 'Character Swap', description: 'Two random superstars exchange characters until after the next WrestleMania-sized event.', category: 'Character' },
  { id: 'forced-alliance', title: 'Forced Alliance', description: 'The top villain and top hero must team together for one month to target the tag champions.', category: 'Rivalry' },
  { id: 'spin-three', title: 'Hat Trick', description: 'Spin the Chaos Wheel three more times and connect the outcomes into one story.', category: 'Chaos' },
  { id: 'spin-five', title: 'You Are In Trouble', description: 'Spin the Chaos Wheel five more times. Treat the result as a major booking crisis.', category: 'Chaos' },
  {"id":"injury-replacement","title":"Injury Replacement","description":"A championship match participant is injured backstage and a random low-card wrestler takes their place.","category":"Pressure"},
  {"id":"forced-vacation","title":"Forced Vacation","description":"The previous main-event winner is exhausted and must miss the next two weeks of competition.","category":"Pressure"},
  {"id":"retirement-announcement","title":"Retirement Announcement","description":"A veteran announces they will retire unless they win a world title at the next PPV.","category":"Pressure"},
  {"id":"loser-changes-brand","title":"Loser Changes Brand","description":"The next rivalry match becomes a Loser Must Change Brand match.","category":"Brands"},
  {"id":"draft-three","title":"Three-for-Three Draft","description":"Each brand randomly selects three superstars to trade to the other brand.","category":"Brands"},
  {"id":"mega-star-switch","title":"Megastar Changes Sides","description":"The highest-rated non-champion moves to the opposing brand and changes the balance of power.","category":"Brands"},
  {"id":"nxt-call-up","title":"Developmental Call-Up","description":"Bring two developmental superstars to a main brand and give them an immediate opportunity.","category":"Brands"},
  {"id":"interbrand-showdown","title":"Interbrand Showdown","description":"Next week becomes a special interbrand show with champions facing champions.","category":"Brands"},
  {"id":"brand-supremacy","title":"Brand Supremacy","description":"The next PPV is brand versus brand. The winning brand earns first choice in the next draft.","category":"Brands"},
  {"id":"protected-champion","title":"Title Protection Rule","description":"A random champion cannot lose their championship for the next month, regardless of the result.","category":"Championship"},
  {"id":"career-vs-title","title":"Career vs. Championship","description":"A championship match at the next PPV becomes Career vs. Title.","category":"Championship"},
  {"id":"title-for-title","title":"Title vs. Title","description":"Two random champions agree to put both championships on the line in one match.","category":"Championship"},
  {"id":"no-champions-month","title":"No Champions Allowed","description":"Champions cannot compete in matches for the next month, forcing new contenders into the spotlight.","category":"Championship"},
  {"id":"champion-handicap","title":"Champion's Pride","description":"A world champion accepts a handicap title defense on the next weekly show.","category":"Championship"},
  {"id":"champion-gauntlet","title":"Champion vs. Champions","description":"The world champion must face every other champion in a non-title gauntlet match.","category":"Championship"},
  {"id":"title-scramble","title":"Championship Scramble","description":"The next world title match becomes a five-person, 20-minute Championship Scramble.","category":"Championship"},
  {"id":"golden-ticket","title":"Golden Ticket","description":"A low-card wrestler finds a Golden Ticket that can be redeemed for any championship match.","category":"Push"},
  {"id":"instant-contender","title":"Lucky Break","description":"A random superstar instantly becomes the number one contender for a championship of your choice.","category":"Push"},
  {"id":"monster-push","title":"Monster Push","description":"A midcard or main-event wrestler receives a world title match at the next PPV.","category":"Push"},
  {"id":"last-chance-series","title":"Last Chance Series","description":"Four low-card wrestlers compete for one month. The wrestler with the most wins receives a secondary title match.","category":"Push"},
  {"id":"giant-challenge","title":"Winner Faces the Giant","description":"The winner of a selected match earns a no-title bout against a dominant giant at the next PPV.","category":"Push"},
  {"id":"low-card-rumble","title":"Low-Card Rumble","description":"Book a 20-person Royal Rumble using only low-card and underused wrestlers.","category":"Push"},
  {"id":"rivalry-reset","title":"Rivalry Reset","description":"A recently concluded rivalry is reset. The wrestlers must shake hands and form a tag team.","category":"Rivalry"},
  {"id":"grudge-rekindled","title":"Grudge Rekindled","description":"A rivalry that ended within the last three months returns after a backstage attack.","category":"Rivalry"},
  {"id":"last-man-standing","title":"Last Man Standing","description":"A current rivalry must conclude in a Last Man Standing Match at the next PPV.","category":"Rivalry"},
  {"id":"forced-tag-rivals","title":"Forced Tag Team","description":"Two active rivals must team together for one month while hunting the tag champions.","category":"Rivalry"},
  {"id":"brawl-before-the-ball","title":"Brawl Before the PPV","description":"The next PPV main event happens early as a non-title match. If the challenger wins, the PPV match becomes No DQ.","category":"Rivalry"},
  {"id":"revenge-clause","title":"Revenge Clause Activated","description":"A former champion receives an automatic rematch next week under I Quit or Submission rules.","category":"Rivalry"},
  {"id":"faction-forms","title":"Faction Forms","description":"Create a new faction of 3 to 5 selected superstars with a shared target.","category":"Faction"},
  {"id":"faction-invasion","title":"Faction Invasion","description":"Five developmental wrestlers form a faction, attack the main event, and demand guaranteed contracts.","category":"Faction"},
  {"id":"masked-attackers","title":"Masked Attackers","description":"Four random wrestlers wear masks and attack every champion for the next two months.","category":"Faction"},
  {"id":"managerial-mayhem","title":"Managerial Mayhem","description":"All wrestlers with managers form a committee and choose one superstar to challenge the world champion.","category":"Authority"},
  {"id":"gm-rivalry","title":"GM Enters the Rivalry","description":"The General Manager enters a rivalry with the world champion that ends in a Bloodline Rules title match.","category":"Authority"},
  {"id":"mystery-gm","title":"Mystery General Manager","description":"A legend replaces the current GM for one night and books matches according to their specialty.","category":"Authority"},
  {"id":"gm-threatened","title":"Threat to the GM","description":"The GM is attacked backstage. The attacker faces them at the PPV with the job on the line.","category":"Authority"},
  {"id":"heel-authority","title":"Heel Authority Figure","description":"The GM allies with the villainous world champion and may interfere once per match for one month.","category":"Authority"},
  {"id":"mitb-stolen","title":"Money in the Bank Breach","description":"A random superstar steals a Money in the Bank briefcase. They fight for it in a Ladder Match.","category":"Special"},
  {"id":"mitb-exchange","title":"Money in the Bank Exchange","description":"A briefcase holder must exchange their contract with another holder or defend it tonight.","category":"Special"},
  {"id":"legend-enforcer","title":"Legend Enforcer","description":"A returning legend becomes the GM's enforcer and targets the GM's biggest rival at the next PPV.","category":"Special"},
  {"id":"gimmick-infringement","title":"Gimmick Infringement","description":"A random superstar copies a legend's entrance, style, and presentation until the legend returns.","category":"Character"},
  {"id":"mirror-image","title":"Mirror Image","description":"A low-ranked superstar copies the world champion exactly until they lose three matches to the real champion.","category":"Character"},
  {"id":"full-character-reboot","title":"Total Repackage","description":"The lowest-rated superstar receives a new character, gear, entrance, and secondary-title push.","category":"Character"},
  {"id":"face-turn","title":"Face Turn","description":"A random villain turns heroic and must prove the change in a match against their former allies.","category":"Character"},
  {"id":"championship-contender-series","title":"Contender Series","description":"Run a four-wrestler singles series for one month to determine a secondary title challenger.","category":"Tournament"},
  {"id":"king-queen-ring","title":"King or Queen of the Ring","description":"Start a tournament that culminates at the next PPV. The winner chooses a title opportunity.","category":"Tournament"},
  {"id":"ultimate-rematch","title":"Ultimate Rematch","description":"Bring back two legends or retired superstars for one final match at the next PPV.","category":"Special"},
  {"id":"main-event-time-limit","title":"Main Event Time Limit","description":"The next PPV main event has a 10-minute limit. If time expires, the champion retains.","category":"Stipulation"},
  {"id":"extreme-rules-month","title":"Extreme Rules Month","description":"Every main event for the next four weeks must use Extreme Rules.","category":"Stipulation"},
]

export const HEATSPARK_WHEEL_CATEGORIES = ['All', ...new Set(HEATSPARK_WHEEL_ENTRIES.map((entry) => entry.category))]
